
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GestionEtudiant", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GestionEtudiant {


    /**
     * 
     * @param mdp
     * @param id
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifier", targetNamespace = "http://service/", className = "service.Modifier")
    @ResponseWrapper(localName = "modifierResponse", targetNamespace = "http://service/", className = "service.ModifierResponse")
    @Action(input = "http://service/GestionEtudiant/modifierRequest", output = "http://service/GestionEtudiant/modifierResponse")
    public String modifier(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "mdp", targetNamespace = "")
        String mdp);

    /**
     * 
     * @param mdp
     * @param login
     * @param nom
     * @param prenom
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouter", targetNamespace = "http://service/", className = "service.Ajouter")
    @ResponseWrapper(localName = "ajouterResponse", targetNamespace = "http://service/", className = "service.AjouterResponse")
    @Action(input = "http://service/GestionEtudiant/ajouterRequest", output = "http://service/GestionEtudiant/ajouterResponse")
    public String ajouter(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "mdp", targetNamespace = "")
        String mdp);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimer", targetNamespace = "http://service/", className = "service.Supprimer")
    @ResponseWrapper(localName = "supprimerResponse", targetNamespace = "http://service/", className = "service.SupprimerResponse")
    @Action(input = "http://service/GestionEtudiant/supprimerRequest", output = "http://service/GestionEtudiant/supprimerResponse")
    public String supprimer(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<service.Etudiant>
     */
    @WebMethod(operationName = "Lister")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Lister", targetNamespace = "http://service/", className = "service.Lister")
    @ResponseWrapper(localName = "ListerResponse", targetNamespace = "http://service/", className = "service.ListerResponse")
    @Action(input = "http://service/GestionEtudiant/ListerRequest", output = "http://service/GestionEtudiant/ListerResponse")
    public List<Etudiant> lister();

}
